### ISSUE TITLE
Debugger instead of dialog when extracting a method

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Calypso#415]
If you try to extract a method that cannot be extracted, you currently will get a debugger instead of a dialog explaining the problem.

To reproduce add this method:

```
aMethod
	|  test |
	test := 1.
	1 to: 10 do: [ test := 2 ].
	test := 4.
	self flag: #todo.
```

Then try to extract 

```
1 to: 10 do: [ test := 2 ].
	test := 4.
	self flag: #todo.
```

@tesonep

**Comment by dionisiydk** [comment]
It is fixed but not integrated.
Commander is still old image. Iceberg update will fix it

ср, 9 янв. 2019 г., 13:15 CyrilFerlicot notifications@github.com:

**Comment by tesonep** [comment]
The error is still present in the latest calypso with latest Commander. 
The execution of the refactorings is completly different in this scenario.

**Comment by dionisiydk** [comment]
Such cases should be fixed on pharo side. Refactorings should raise
RefactoringError's instead of basic Error

ср, 9 янв. 2019 г., 13:52 Pablo Tesone notifications@github.com:
